{% set name = "ktextwidgets" %}
{% set version = "5.69.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/ktextwidgets-{{ version }}.tar.xz
  sha256: 182661253bf2ed940ab52edfeb2d8cadf1abbde76cade2ba50ef490311002ec9

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('ktextwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - sonnet
    - ki18n
    - kservice
    - kconfig
    - kcoreaddons
    - kcompletion
    - kwidgetsaddons
    - kwindowsystem
    - kconfigwidgets
    - xcb-util-keysyms

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5TextWidgets.so

about:
  home: https://api.kde.org/frameworks/ktextwidgets/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Text editing widgets
  description: |
    KTextWidgets provides widgets for displaying and editing text. It supports
    rich text as well as plain text.
  dev_url: https://cgit.kde.org/ktextwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
