{% set name = "ktextwidgets" %}
{% set version = "5.70.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/ktextwidgets-{{ version }}.tar.xz
  sha256: fc1057c291e44a2fe7c971f3e3695924acb0f648932bc8539ee418b538cd0998

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('ktextwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - sonnet >={{ version }}
    - ki18n >={{ version }}
    - kservice >={{ version }}
    - kconfig >={{ version }}
    - kcoreaddons >={{ version }}
    - kcompletion >={{ version }}
    - kwidgetsaddons >={{ version }}
    - kwindowsystem >={{ version }}
    - kconfigwidgets >={{ version }}
    - xcb-util-keysyms

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5TextWidgets.so

about:
  home: https://api.kde.org/frameworks/ktextwidgets/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Text editing widgets
  description: |
    KTextWidgets provides widgets for displaying and editing text. It supports
    rich text as well as plain text.
  dev_url: https://cgit.kde.org/ktextwidgets.git/tree

extra:
  recipe-maintainers:
    - scopatz
